version: "3.9"
services:
  api:
    build:
      context: $PWD
      dockerfile: api/Dockerfile
    container_name: sf-academy-api
    working_dir: /home/node/app/api
    ports:
      - ${API_PORT}:${API_PORT}
    environment:
      NODE_ENV: ${NODE_ENV}
      API_PORT: ${API_PORT}
      EXCHANGE_PORT: ${EXCHANGE_PORT}
      EXCHANGE_HOST: ${EXCHANGE_HOST}
      USERS_PORT: ${USERS_PORT}
      USERS_HOST: ${USERS_HOST}
      TOKEN_SECRET: ${TOKEN_SECRET}
    entrypoint: node build/server/src/index.js
  exchange:
    build:
      context: $PWD
      dockerfile: exchange/Dockerfile
    container_name: sf-academy-exchange
    working_dir: /home/node/app/exchange
    ports:
      - ${EXCHANGE_PORT}:${EXCHANGE_PORT}
    environment:
      NODE_ENV: ${NODE_ENV}
      EXCHANGE_PORT: ${EXCHANGE_PORT}
    entrypoint: node build/server/src/index.js
  users:
    build:
      context: $PWD
      dockerfile: users/Dockerfile
    container_name: sf-academy-users
    working_dir: /home/node/app/users
    ports:
      - ${USERS_PORT}:${USERS_PORT}
    environment:
      NODE_ENV: ${NODE_ENV}
      USERS_PORT: ${USERS_PORT}
      TOKEN_SECRET: ${TOKEN_SECRET}
    entrypoint: node build/server/src/index.js
    