openapi: 3.0.3
info:
  title: Sf Academy
  version: 1.0.0
  description: Generated docs from my candidacy test
paths:
  /exchange:
    get:
      description: Converts to other currency
      operationId: exchange
      x-eov-operation-handler: routes/exchange
      parameters:
        - name: value
          in: query
          required: true
          schema:
            type: number
            minimum: 1
            maximum: 1000000
            nullable: false
        - name: from
          in: query
          schema:
            allOf:
              - $ref: "./schemas/currency.yaml"
        - name: to
          in: query
          schema:
            allOf:
              - $ref: "./schemas/currency.yaml"
      responses:
        "200":
          description: Succesful exchange
          content:
            application/json:
              schema:
                allOf:
                  - $ref: ./schemas/amount.yaml
  /login:
    post:
      description: Release a JWT on succesful login
      operationId: login
      x-eov-operation-handler: routes/login
      requestBody:
        content:
          application/json:
            schema:
              allOf:
                - $ref: "./schemas/userCredentials.yaml"
      responses:
        "200":
          description: Succesful login
          content:
            application/json:
              schema:
                $ref: "./schemas/okResponse.yaml"
        "401":
          description: Invalid credentials
          content:
            application/json:
              schema:
                $ref: "./schemas/errorResponse.yaml"
  /listTransactions:
    get:
      description: Returns the list of transactions of authenticated user
      operationId: listTransactions
      x-eov-operation-handler: routes/listTransactions
      parameters:
        - name: userId
          in: query
          schema:
            type: integer
          required: true
      responses:
        "200":
          description: Succesful list
          content:
            application/json:
              schema:
                type: array
                items:
                  allOf:
                    - $ref: "./schemas/transaction.yaml"
                  required:
                    - eurDelta
                    - usdDelta
                    - date
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "./schemas/errorResponse.yaml"
      security:
        - bearerAuth: []
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT