openapi: 3.0.3
info:
  title: Sf Academy
  version: 1.0.0
  description: Generated docs from my candidacy test
paths:
  /exchange:
    get:
      description: Converts to other currency
      operationId: exchange
      x-eov-operation-handler: routes/exchange
      parameters:
        - name: value
          in: query
          required: true
          schema:
            type: number
            minimum: 0
            exclusiveMinimum: true
            nullable: false
        - name: from
          in: query
          required: true
          schema:
            $ref: "./schemas/currency.yaml"
        - name: to
          in: query
          required: true
          schema:
            $ref: "./schemas/currency.yaml"
      responses:
        '200':
          description: Succesful response
          content:
            application/json:
              schema:
                $ref: ./schemas/amount.yaml